const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.join(__dirname,'..'),html=fs.readFileSync(path.join(root,'dashboard.html'),'utf8');
const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length,'Duplicate dashboard IDs');
const sectionStack=[];for(const m of html.matchAll(/<\/?section\b[^>]*>|<[^>]+\bid="storageRows"[^>]*>/g)){if(m[0].startsWith('</section')){assert.ok(sectionStack.length,'Unmatched section end');sectionStack.pop()}else if(m[0].startsWith('<section'))sectionStack.push(m[0].match(/\bid="([^"]+)"/)?.[1]);else assert.ok(sectionStack.includes('panel-overview'),'Storage outside Overview')}assert.equal(sectionStack.length,0,'Unclosed dashboard section');
class Element{
 constructor(attrs={}){this.attrs=attrs;this.children=[];this.textContent='';this.style={};this.clientWidth=800;this.clientHeight=248;this.disabled=false;this.value='';this.hidden=attrs.hidden!==undefined;this.paints=0}
 append(...e){this.children.push(...e)}replaceChildren(...e){this.children=e;this.paints++}setAttribute(k,v){this.attrs[k]=v}getAttribute(k){return this.attrs[k]}focus(){}remove(){}click(){this.onclick?.()}
 getContext(){return new Proxy({},{get:(target,key)=>target[key]||(()=>{}),set:(target,key,val)=>{target[key]=val;return true}})}
}
const elements=new Map();for(const match of html.matchAll(/<[^>]+\bid="([^"]+)"[^>]*>/g)){const attrs=Object.fromEntries([...match[0].matchAll(/([\w-]+)="([^"]*)"/g)].map(m=>[m[1],m[2]]));if(/\shidden(?:\s|>)/.test(match[0]))attrs.hidden='';const el=new Element(attrs);el.id=match[1];elements.set(el.id,el)}
const get=id=>{assert.ok(elements.has(id),'Missing DOM element: '+id);return elements.get(id)},tabs=[...elements.values()].filter(e=>e.attrs.role==='tab');
const timers=[],events=new Map(),store=new Map();const context={console,Date,Map,Set,AbortController,Event:class{constructor(type){this.type=type}},setInterval:fn=>timers.push(fn),setTimeout:()=>0,clearTimeout(){},localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},document:{getElementById:get,createElement:()=>new Element(),head:new Element(),querySelectorAll:selector=>{assert.equal(selector,'[role="tab"]');return tabs}},addEventListener:(k,fn)=>events.set(k,fn),dispatchEvent:e=>events.get(e.type)?.(),devicePixelRatio:1};context.window=context;
vm.createContext(context);
for(const script of html.matchAll(/<script(?: src="([^"]+)")?>([\s\S]*?)<\/script>/g))vm.runInContext(script[1]?fs.readFileSync(path.join(root,script[1]),'utf8'):script[2],context,{filename:script[1]||'dashboard.html'});
assert.equal(tabs.length,7);assert.equal(get('panel-overview').hidden,false);assert.equal(get('panel-frames').hidden,true);
const base={session:'test',generated_at:new Date().toISOString(),game:'ACOrigins.exe',game_pid:7,container:'com.tencent.ig',backend:'DXVK',target_fps:60,assessment:'No clear pressure',evidence:'Test',next_check:'Same scene',csv_path:'local.csv',monitoring:{collector_state:'running',scheduler_stats_enabled:true},cpu:{game_ms_per_s:4500,cores:[],cores_over_90:1},memory:{available_mb:3000,game_rss_mb:2500},gpu:{busy_percent:99,recent_busy_percent:98},surface:{p95_ms:29,updates:60,spikes_33:0,spikes_50:0,intervals_ms:[25,26]},thermal:{sensors:[]},jit:{status:'Unavailable'},app_profile:{fps:40,p95_ms:27,game:'Origins',status:'Live app HUD',intervals_ms:[25,26]},history:[],layers:[],events:[]};
context.renderProfileData(base);assert.equal(get('hudFps').textContent,'40.0');assert.equal(get('hudP95').textContent,'27.0 ms');assert.match(get('statusText').textContent,/Live/);
assert.equal(get('gameThreadRows').paints,0);assert.equal(get('graphicsActivityRows').paints,0);
const paints=get('memoryRows').paints;context.renderProfileData(base);assert.equal(get('memoryRows').paints,paints);
for(const tab of tabs){tab.onclick();assert.equal(get(tab.getAttribute('aria-controls')).hidden,false);assert.equal(tabs.filter(t=>t.getAttribute('aria-selected')==='true').length,1)}
context.renderProfileData({...base,monitoring:{collector_state:'stopped',scheduler_stats_enabled:true}});assert.match(get('statusText').textContent,/frozen/);get('tab-cpu').onclick();assert.match(get('cpuQueueStatus').textContent,/Stopped/);assert.match(get('threadTimelineStatus').textContent,/Stopped/);get('tab-graphics').onclick();assert.match(get('graphicsActivityStatus').textContent,/Stopped/);assert.equal(get('pinBaseline').disabled,true);
context.renderProfileData({...base,game:'Unavailable',game_pid:null,app_profile:{fps:null,p95_ms:null,status:'Idle'},gpu:{busy_percent:null},monitoring:{collector_state:'running',scheduler_stats_enabled:false}});get('tab-overview').onclick();assert.equal(get('hudFps').textContent,'—');assert.equal(get('gpu').textContent,'—');assert.equal(get('hudP95').textContent,'—');get('tab-cpu').onclick();assert.match(get('cpuQueueRows').textContent,/off/);
context.renderProfileData({...base,generated_at:new Date(Date.now()-20000).toISOString()});assert.match(get('statusText').textContent,/Disconnected/);
context.renderProfileData({...base,generated_at:new Date().toISOString(),storage:{status:'Possible storage stalls',evidence:'Sampled evidence',game_major_faults_s:10,game_blocked_threads:1,io_wait_percent:3,throughput_status:'Unavailable: permission denied'},storage_history:[{io_wait_percent:3,frame_p95_ms:60}]});get('tab-overview').onclick();
assert.equal(get('storageStatus').textContent,'Possible storage stalls');assert.equal(get('storageEvidence').textContent,'Sampled evidence');
assert.ok(get('storageRows').children.some(r=>r.children.some(c=>c.textContent==='Unavailable: permission denied')));
context.renderProfileData({...base,monitoring:{collector_state:'stopped'},storage:{status:'No strong storage-stall evidence'}});assert.match(get('storageStatus').textContent,/Stopped.*frozen/);
context.renderProfileData({...base,generated_at:new Date().toISOString()});assert.match(get('storageStatus').textContent,/updated collector/);
const storageRow=get('storageRows').children.find(r=>r.children[0].textContent==='Game major page faults');assert.equal(storageRow.children[1].textContent,'—');
const alertAt=Date.now()-9000,alertSample=(i,fps,p95=16)=>({...base,session:'change-ui',generated_at:new Date(alertAt+i*3000).toISOString(),app_profile:{session:'ui-game',fps,p95_ms:p95}});
get('tab-graphics').onclick();for(let i=0;i<3;i++)context.renderProfileData(alertSample(i,60));context.renderProfileData(alertSample(3,35));
assert.match(get('changeBadge').textContent,/1 new change/);assert.equal(get('changeToast').hidden,false);assert.equal(get('hudFps').getAttribute('data-sudden-change'),'true');assert.equal(get('changeSound').getAttribute('aria-pressed'),'false');
get('changeToast').click();assert.equal(get('panel-overview').hidden,false);assert.ok(get('changeEvents').children.length);const historySize=get('changeEvents').children[0].children.length;
get('ackChanges').click();assert.equal(get('changeToast').hidden,true);assert.equal(get('ackChanges').disabled,true);assert.equal(get('changeEvents').children[0].children.length,historySize,'Acknowledge erased history');
let beeps=0,suspended=false;context.AudioContext=class{constructor(){this.state='suspended';this.currentTime=0;this.destination={}}async resume(){this.state='running'}async suspend(){this.state='suspended';suspended=true}createOscillator(){return {frequency:{setValueAtTime(){}},connect(){},disconnect(){},start(){beeps++},stop(){}}}createGain(){return {gain:{setValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){},disconnect(){}}}};
(async()=>{await get('changeSound').onclick();assert.equal(get('changeSound').textContent,'Sound: on');assert.equal(get('changeSound').getAttribute('aria-pressed'),'true');context.renderProfileData(alertSample(4,15,45));assert.equal(beeps,1,'One tone required per alert batch');context.renderProfileData(alertSample(4,15,45));assert.equal(beeps,1,'Duplicate snapshot sounded');await get('changeSound').onclick();assert.equal(get('changeSound').textContent,'Sound: off');assert.ok(suspended);console.log('PASS: complete dashboard, storage, cross-tab change alerts, metric highlight, retained acknowledgment and opt-in batch sound')})().catch(error=>{console.error(error);process.exitCode=1});
