const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.join(__dirname,'..'),html=fs.readFileSync(path.join(root,'dashboard.html'),'utf8');
const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length,'Duplicate dashboard IDs');
class Element{
 constructor(attrs={}){this.attrs=attrs;this.children=[];this.textContent='';this.style={};this.clientWidth=800;this.clientHeight=248;this.disabled=false;this.value='';this.hidden=attrs.hidden!==undefined}
 append(...e){this.children.push(...e)}replaceChildren(...e){this.children=e}setAttribute(k,v){this.attrs[k]=v}getAttribute(k){return this.attrs[k]}focus(){}remove(){}click(){this.onclick?.()}
 getContext(){return new Proxy({},{get:(target,key)=>target[key]||(()=>{}),set:(target,key,val)=>{target[key]=val;return true}})}
}
const elements=new Map();for(const match of html.matchAll(/<[^>]+\bid="([^"]+)"[^>]*>/g)){const attrs=Object.fromEntries([...match[0].matchAll(/([\w-]+)="([^"]*)"/g)].map(m=>[m[1],m[2]]));if(/\shidden(?:\s|>)/.test(match[0]))attrs.hidden='';const el=new Element(attrs);el.id=match[1];elements.set(el.id,el)}
const get=id=>{assert.ok(elements.has(id),'Missing DOM element: '+id);return elements.get(id)},tabs=[...elements.values()].filter(e=>e.attrs.role==='tab');
const timers=[],events=new Map(),store=new Map();const context={console,Date,Map,Set,AbortController,Event:class{constructor(type){this.type=type}},setInterval:fn=>timers.push(fn),setTimeout:()=>0,clearTimeout(){},localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},document:{getElementById:get,createElement:()=>new Element(),head:new Element(),querySelectorAll:selector=>{assert.equal(selector,'[role="tab"]');return tabs}},addEventListener:(k,fn)=>events.set(k,fn),dispatchEvent:e=>events.get(e.type)?.(),devicePixelRatio:1};context.window=context;
vm.createContext(context);
for(const script of html.matchAll(/<script(?: src="([^"]+)")?>([\s\S]*?)<\/script>/g))vm.runInContext(script[1]?fs.readFileSync(path.join(root,script[1]),'utf8'):script[2],context,{filename:script[1]||'dashboard.html'});
assert.equal(tabs.length,7);assert.equal(get('panel-overview').hidden,false);assert.equal(get('panel-frames').hidden,true);
const base={session:'test',generated_at:new Date().toISOString(),game:'ACOrigins.exe',game_pid:7,container:'com.tencent.ig',backend:'DXVK',target_fps:60,assessment:'No clear pressure',evidence:'Test',next_check:'Same scene',csv_path:'local.csv',monitoring:{collector_state:'running',scheduler_stats_enabled:true},cpu:{game_ms_per_s:4500,cores:[],cores_over_90:1},memory:{available_mb:3000,game_rss_mb:2500},gpu:{busy_percent:99,recent_busy_percent:98},surface:{p95_ms:29,updates:60,spikes_33:0,spikes_50:0,intervals_ms:[25,26]},thermal:{sensors:[]},jit:{status:'Unavailable'},app_profile:{fps:40,p95_ms:27,game:'Origins',status:'Live app HUD',intervals_ms:[25,26]},history:[],layers:[],events:[]};
context.renderProfileData(base);assert.equal(get('hudFps').textContent,'40.0');assert.equal(get('hudP95').textContent,'27.0 ms');assert.match(get('statusText').textContent,/Live/);
for(const tab of tabs){tab.onclick();assert.equal(get(tab.getAttribute('aria-controls')).hidden,false);assert.equal(tabs.filter(t=>t.getAttribute('aria-selected')==='true').length,1)}
context.renderProfileData({...base,monitoring:{collector_state:'stopped',scheduler_stats_enabled:true}});assert.match(get('statusText').textContent,/frozen/);assert.match(get('cpuQueueStatus').textContent,/Stopped/);assert.match(get('graphicsActivityStatus').textContent,/Stopped/);assert.match(get('threadTimelineStatus').textContent,/Stopped/);assert.equal(get('pinBaseline').disabled,true);
context.renderProfileData({...base,game:'Unavailable',game_pid:null,app_profile:{fps:null,p95_ms:null,status:'Idle'},gpu:{busy_percent:null},monitoring:{collector_state:'running',scheduler_stats_enabled:false}});assert.equal(get('hudFps').textContent,'—');assert.equal(get('gpu').textContent,'—');assert.equal(get('hudP95').textContent,'—');assert.match(get('cpuQueueRows').textContent,/off/);
context.renderProfileData({...base,generated_at:new Date(Date.now()-20000).toISOString()});assert.match(get('statusText').textContent,/Disconnected/);
console.log('PASS: complete dashboard render, all tab views, DOM coverage, live/stopped/missing/disconnected states');
