const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {stopUrl,actionUrl}=require('../scripts/monitor-control.js');
const url='http://127.0.0.1:12345/stop/'+'a'.repeat(32);
const resume=url.replace('/stop/','/resume/');
assert.equal(stopUrl({monitoring:{stop_url:url}}),url);
for(const bad of ['https://example.com/stop','http://localhost:123/stop/'+'a'.repeat(32),url+'/extra'])assert.equal(stopUrl({monitoring:{stop_url:bad}}),null);
const button={disabled:true},message={},timers=[];let requests=0;
const context={document:{getElementById:id=>id==='stopMonitoring'?button:message},window:{renderProfileData(){}},Date,AbortController,setInterval:fn=>timers.push(fn),setTimeout,clearTimeout,fetch:async(u,opts)=>{assert.equal(u,requests===0?url:resume);assert.equal(opts.method,'POST');requests++;return {ok:true,json:async()=>({ok:true})}}};
vm.runInNewContext(fs.readFileSync(require.resolve('../scripts/monitor-control.js'),'utf8'),context);
const sample={session:'one',generated_at:new Date().toISOString(),monitoring:{collector_state:'running',stop_url:url,resume_url:resume,can_resume:true,control_updated_at:new Date().toISOString()}};
(async()=>{
 context.window.renderProfileData(sample);assert.equal(button.disabled,false);
 await button.onclick();assert.equal(requests,1);assert.equal(button.disabled,false);assert.equal(button.textContent,'Resume monitoring');assert.match(message.textContent,/game and phone profiling exporter continue/);
 context.window.renderProfileData({...sample,generated_at:new Date(Date.now()-20000).toISOString()});assert.equal(button.disabled,false);
 await button.onclick();assert.equal(requests,2);assert.equal(button.textContent,'Stop monitoring');
 assert.equal(actionUrl(sample,'resume'),resume);
 context.window.renderProfileData({...sample,session:'two',monitoring:{collector_state:'running',stop_url:url}});assert.equal(button.disabled,false);
 context.window.renderProfileData({...sample,generated_at:new Date(Date.now()-20000).toISOString(),monitoring:{collector_state:'running',stop_url:url}});assert.equal(button.disabled,true);
 context.window.renderProfileData({...sample,monitoring:{...sample.monitoring,collector_state:'stopped',can_resume:false}});assert.equal(button.disabled,true);
 console.log('PASS: stop/resume actions, frozen readings with live controls, ended collector and stale disabling');
})().catch(e=>{console.error(e);process.exitCode=1});
